name: Ejecutar código Java
run: java -cp . Pelicula.Main

on: [push, pull_request] 

jobs:
  run-java:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Configurar Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' 
          java-version: '17' 

      - name: Compilar el código
        run: javac Main.java

      - name: Ejecutar el código
        run: java Main
